export const ADDACCESSTOKEN = "ADDACCESSTOKEN"
export const ADDREDDITDATA = "ADDREDDITDATA"
export const ADDREDDITUSERNAME = "ADDREDDITUSERNAME"

export const DELETEONE = "DELETEONE"

export const RESET = "RESET"
